package com.app.feenix.model.request

data class SendRideRequest(
    val s_latitude: Double?,
    val s_longitude: Double?,
    val d_latitude: Double?,
    val d_longitude: Double?,
    val service_type: Int?,
    val schedule_date: String?,
    val schedule_time: String?,
    val use_wallet: Int?,
    val payment_mode: String?,
    val s_title: String?,
    val s_address: String?,
    val d_title: String?,
    val d_address: String?,
    val card_id: String?,
    val receiver_name: String?,
    val receiver_mobile: String?,
    val pickup_instruction: String?,
    val delivery_instruction: String?,
    val package_details: String?,
    val package_type: String?,
    val estimated_fare: String?,
    val distance: String?,
    val distance_price: String?,
    val time: String?,
    val time_price: String?,
    val tax_price: String?,
    val base_price: String?,
    val wallet_balance: String?,
    val discount: String?,
    val pickup_note: String?
)
